version: '3.5'
services:
  auth_service:
    build: .
    container_name: book_exchange_auth_service
    env_file: .env
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    restart: always
    networks:
      - auth_network
    depends_on:
      - auth_progresql
      - auth_redis

  auth_progresql:
    image: postgres:latest
    container_name: book_exchange_auth_progresql
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    networks:
      - auth_network
    volumes:
      - postgres_data:${PGDATA}
  
  auth_redis:
    image: redis:latest
    container_name: book_exchange_auth_redis
    env_file: .env
    command: >
          --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    networks:
      - auth_network

networks:
  auth_network:

volumes:
  postgres_data:


