export const configKeys = {
  HTTP_SERVER_PORT: 'HTTP_SERVER_PORT',
  JWT_SECRET: 'JWT_SECRET',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_DB: 'REDIS_DB',
};
