name: CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0

      - name: "Setup environment"
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: "Install dependencies"
        run: pnpm install
        
      - name: "Lint"
        run: |
          npm run lint

      - name: "Test"
        run: |
          npm run test

  docker-deploy:
    needs:
      - pre-docker-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: indiedevs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tag: indiedevs/book-exchange-auth-service
