name: CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0

      - name: "Setup environment"
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: "Install dependencies"
        run: pnpm install
        
      - name: "Lint"
        run: |
          npm run lint

      - name: "Test"
        run: |
          npm run test

      - name: "Build"
        needs:
          - lint
          - test
        run: |
          npm run build


