name: Prebuild
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-quality-and-prebuild:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0

      - name: "Setup environment"
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - 
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Ho_Chi_Minh"
      
      - name: "Install dependencies"
        run: pnpm install
        
      - name: "Lint"
        run: |
          npm run lint

      - name: "Test"
        run: |
          npm run test

      - name : "Build"
        run: |
          npm run build

